# This workflow will compile the Python distribution package in the dist/
# directory and upload it to PyPI

name: publish

on:
  release:
    types:
      - published

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip

      - name: Build binary wheel and source tarball 🔨
        run: |
          python -m pip install build
          python -m build

#      - name: Publish distribution 📦 to Test PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'release' && github.event.release.target_commitish == 'main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
